version: '3.5'

services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "8388:8388"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=9MLSpPmNt
    restart: always

  kcptun:
    image: vimagick/kcptun
    command:
      --listen :29900
      --target shadowsocks:8388
      --crypt aes
      --mode fast
    depends_on:
      - shadowsocks
    ports:
    - "29900:29900/udp"
    environment:
      - KCPTUN_KEY = "VVqwMf+qDtulHJC7dPR/dPsCW8SYAeCFaP0TMWFNiLg="
    restart: always
